[package]
name = "kconfigurator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
load_file = "1.0.1"
nom = "7.1.1"
